# SPDX-License-Identifier: GPL-2.0
KERNDIR ?= /lib/modules/$(shell uname -r)/build
TEST_GEN_PROGS := scullpm_sysfs_test
TEST_GEN_PROGS += scullpm_procfs_test
include $(KERNDIR)/tools/testing/selftests/lib.mk
